config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'about#index'
  
  root 'index#index'
  
  resources :categories, only: [:index, :show, :search] do
    member do
      get 'search'
    end
  end
  
  resources :packages, only: [:index, :show, :search] do
    collection do
      get 'search'
      get 'suggest'
      get 'resolve'
      get 'added'
      get 'updated'
      get 'stable'
      get 'keyworded'
    end
  end
end

app/models/category.rb
require 'active_record'
ActiveRecord::Base.establish_connection( adapter: 'postgresql', database: ":archive_development:" )

class Category
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  include Kkuleomi::Store::Model
  
# Determines if the document model needs an update from the repository model
  #
  # @param [Portage::Repository::Category] category_model
  def needs_import?(category_model)
    metadata_hash != category_model.metadata_hash
  end

  # Populates values from a repository category model
  #
  # @param [Portage::Repository::Category] category_model Input category model
  def import(category_model)
    self.name = category_model.name
    self.description = category_model.description
    self.metadata_hash = category_model.metadata_hash
  end

  # Populates values from a repository category model and saves
  #
  # @param [Portage::Repository::Category] category_model Input category model
  def import!(category_model)
    import(category_model)
    save
  end

  # Returns the URL parameter for referencing this package (Rails internal stuff)
  def to_param
    name
  end
end

app/models/portage/repository/category.rb
require 'digest'

class Portage::Repository::Category
  attr_reader :name, :path

  # Creates a new Category model
  #
  # @param [String] path Category base directory path
  def initialize(path)
    unless File.directory? path
      raise ArgumentError, "#{path} does not look like a valid category for repository."
    end

    @path = path
    @name = path.split('/').last
  end

  # Returns the description of the category in English, or the requested language
  #
  # @param [Symbol] lang Requested description language
  # @return [String] Description, or nil if no description for this language is included in the metadata
  def description(lang = :en)
    metadata[lang.to_sym]
  end

  # Returns a list of available description languages
  #
  # @return [Array] Available language symbols
  def description_languages
    metadata.keys.sort
  end

  # Returns a list of packages in this category
  #
  # @return [Array] List of packages in this category
  def packages
    @packages ||= package_dirs.map {|p| Portage::Repository::Package.new(p) }
  end


  # Returns a given package, or nil
  #
  # TODO: Hash categories internally?
  def package(name)
    packages.each do |package|
      return package if package.name == name
    end

    nil
  end


  # Returns the hash of the metadata for this category
  #
  # @return [String] MD5 hash of the category metadata
  def metadata_hash
    Digest::MD5.file(File.join(@path, 'metadata.xml')).hexdigest
  end

  private
  def metadata
    @metadata ||= parse_metadata
  end

  def parse_metadata
    f = File.open(File.join(@path, 'metadata.xml'))
    xml = Nokogiri::XML(f)
    f.close

    res = {}

    xml.xpath('/catmetadata/longdescription').each do |desc_tag|
      lang = :en
      lang = desc_tag['lang'].downcase.to_sym if desc_tag.has_attribute? 'lang'

      res[lang] = desc_tag.text.strip.gsub(/\s+/, ' ')
    end

    res
  rescue Errno::ENOENT
    Rails.logger.warn "Cannot find metadata for category #{@name}."
    {}
  end

  # Filters the subdirectories of the category to find packages
  #
  # @return [Array] Package directories in this category
  def package_dirs
    Dir.glob("#{@path}/*").select do |d|
      File.directory?(d) and File.file?(File.join(d, 'metadata.xml'))
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.fetch(:category, {})
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>